environment:
  nodejs_version: "5"
cache:
- C:\Program Files (x86)\nodejs\node_modules\npm\node_modules
- C:\Users\appveyor\AppData\Roaming\npm
- C:\Users\appveyor\AppData\Roaming\npm-cache
version: '{build}'
branches:
  only:
  - master
install:
  - appveyor DownloadFile http://downloads.sourceforge.net/graphicsmagick/GraphicsMagick-1.3.20-Q8-win32-dll.exe
  - GraphicsMagick-1.3.20-Q8-win32-dll.exe /SP /VERYSILENT /NORESTART /NOICONS /DIR=%CD%\gm
  - set PATH=%CD%\gm;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run test-ci
build: off